development:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: myapp_development

test:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: myapp_test

production:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: myapp_production
